env:
  es2021: true
  node: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  computed-property-spacing:
    - error
    - never
  comma-dangle: off
  no-duplicate-imports: error
  array-bracket-spacing:
    - error
    - never
  block-scoped-var: error
  brace-style: off
  curly: error
  eol-last: error
  eqeqeq:
    - error
    - smart
  max-depth:
    - 1
    - 5
  max-statements:
    - 1
    - 80
  no-multiple-empty-lines: error
  no-mixed-spaces-and-tabs: error
  no-trailing-spaces: error
  no-undef: error
  no-var: error
  object-curly-spacing: off
